
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action openAction;
	private global::Gtk.ToggleAction quitAction;
	private global::Gtk.Action Action;
	private global::Gtk.Action quitAction1;
	private global::Gtk.Action refreshAction;
	private global::Gtk.Action refreshAction1;
	private global::Gtk.Action saveAsAction;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action AboutAction;
	private global::Gtk.Action ViewAction;
	private global::Gtk.RadioAction RowWiseAction;
	private global::Gtk.RadioAction ColWiseAction;
	private global::Gtk.ToggleAction RowwiseAction;
	private global::Gtk.ToggleAction RowwiseSelector;
	private global::Gtk.ToggleAction RowwiseAction1;
	private global::Gtk.Action ViewAction1;
	private global::Gtk.ToggleAction ColumnWiseAction;
	private global::Gtk.VBox vbox2;
	private global::Gtk.MenuBar menubar2;
	private global::Gtk.HBox hbox1;
	private global::Gtk.VSeparator vseparator2;
	private global::Gtk.HBox hbox2;
	private global::Gtk.VBox vbox3;
	private global::Gtk.SpinButton spinbutton;
	private global::Gtk.FileChooserWidget filechooserwidget;
	private global::Gtk.HPaned hpaned1;
	private global::Gtk.VPaned vpaned1;
	private global::Gtk.HPaned hpaned3;
	private global::Gtk.VPaned vpaned2;
	private global::Gtk.Image matrixImage;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("Open"), null, "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.openAction, null);
		this.quitAction = new global::Gtk.ToggleAction ("quitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.quitAction, null);
		this.Action = new global::Gtk.Action ("Action", global::Mono.Unix.Catalog.GetString ("_"), null, null);
		this.Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("_");
		w1.Add (this.Action, null);
		this.quitAction1 = new global::Gtk.Action ("quitAction1", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
		this.quitAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.quitAction1, null);
		this.refreshAction = new global::Gtk.Action ("refreshAction", global::Mono.Unix.Catalog.GetString ("_Refresh"), null, "gtk-refresh");
		this.refreshAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Refresh");
		w1.Add (this.refreshAction, null);
		this.refreshAction1 = new global::Gtk.Action ("refreshAction1", global::Mono.Unix.Catalog.GetString ("_Refresh"), null, "gtk-refresh");
		this.refreshAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Refresh");
		w1.Add (this.refreshAction1, null);
		this.saveAsAction = new global::Gtk.Action ("saveAsAction", global::Mono.Unix.Catalog.GetString ("Save a copy..."), null, "gtk-save-as");
		this.saveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save a copy...");
		w1.Add (this.saveAsAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.ViewAction = new global::Gtk.Action ("ViewAction", global::Mono.Unix.Catalog.GetString ("View"), null, null);
		this.ViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View");
		w1.Add (this.ViewAction, null);
		this.RowWiseAction = new global::Gtk.RadioAction ("RowWiseAction", global::Mono.Unix.Catalog.GetString ("Row-wise"), null, null, 0);
		this.RowWiseAction.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.RowWiseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Row-wise");
		w1.Add (this.RowWiseAction, null);
		this.ColWiseAction = new global::Gtk.RadioAction ("ColWiseAction", global::Mono.Unix.Catalog.GetString ("Col-wise"), null, null, 0);
		this.ColWiseAction.Group = this.RowWiseAction.Group;
		this.ColWiseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Col-wise");
		w1.Add (this.ColWiseAction, null);
		this.RowwiseAction = new global::Gtk.ToggleAction ("RowwiseAction", global::Mono.Unix.Catalog.GetString ("Rowwise"), null, null);
		this.RowwiseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Rowwise");
		w1.Add (this.RowwiseAction, null);
		this.RowwiseSelector = new global::Gtk.ToggleAction ("RowwiseSelector", global::Mono.Unix.Catalog.GetString ("Rowwise"), null, null);
		this.RowwiseSelector.Active = true;
		this.RowwiseSelector.ShortLabel = global::Mono.Unix.Catalog.GetString ("Rowwise");
		w1.Add (this.RowwiseSelector, null);
		this.RowwiseAction1 = new global::Gtk.ToggleAction ("RowwiseAction1", global::Mono.Unix.Catalog.GetString ("Rowwise"), null, null);
		this.RowwiseAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Rowwise");
		w1.Add (this.RowwiseAction1, null);
		this.ViewAction1 = new global::Gtk.Action ("ViewAction1", global::Mono.Unix.Catalog.GetString ("View"), null, null);
		this.ViewAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("View");
		w1.Add (this.ViewAction1, null);
		this.ColumnWiseAction = new global::Gtk.ToggleAction ("ColumnWiseAction", global::Mono.Unix.Catalog.GetString ("Column wise"), null, null);
		this.ColumnWiseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("RowWise");
		w1.Add (this.ColumnWiseAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'><menuitem name='openAction' action='openAction'/><menuitem name='refreshAction1' action='refreshAction1'/><menuitem name='saveAsAction' action='saveAsAction'/><separator/><menuitem name='quitAction1' action='quitAction1'/></menu><menu name='ViewAction1' action='ViewAction1'><menuitem name='ColumnWiseAction' action='ColumnWiseAction'/></menu><menu name='HelpAction' action='HelpAction'/></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox2.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vseparator2 = new global::Gtk.VSeparator ();
		this.vseparator2.Name = "vseparator2";
		this.hbox1.Add (this.vseparator2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vseparator2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.WidthRequest = 460;
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.spinbutton = new global::Gtk.SpinButton (0, 100, 1);
		this.spinbutton.Sensitive = false;
		this.spinbutton.CanFocus = true;
		this.spinbutton.Name = "spinbutton";
		this.spinbutton.Adjustment.PageIncrement = 10;
		this.spinbutton.ClimbRate = 1;
		this.spinbutton.Numeric = true;
		this.vbox3.Add (this.spinbutton);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.spinbutton]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.filechooserwidget = new global::Gtk.FileChooserWidget (((global::Gtk.FileChooserAction)(0)));
		this.filechooserwidget.Name = "filechooserwidget";
		this.vbox3.Add (this.filechooserwidget);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.filechooserwidget]));
		w5.Position = 1;
		this.hbox2.Add (this.vbox3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox3]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 109;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 56;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.hpaned3 = new global::Gtk.HPaned ();
		this.hpaned3.CanFocus = true;
		this.hpaned3.Name = "hpaned3";
		this.hpaned3.Position = 418;
		// Container child hpaned3.Gtk.Paned+PanedChild
		this.vpaned2 = new global::Gtk.VPaned ();
		this.vpaned2.CanFocus = true;
		this.vpaned2.Name = "vpaned2";
		this.vpaned2.Position = 386;
		// Container child vpaned2.Gtk.Paned+PanedChild
		this.matrixImage = new global::Gtk.Image ();
		this.matrixImage.Name = "matrixImage";
		this.matrixImage.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-missing-image", global::Gtk.IconSize.Menu);
		this.vpaned2.Add (this.matrixImage);
		global::Gtk.Paned.PanedChild w7 = ((global::Gtk.Paned.PanedChild)(this.vpaned2 [this.matrixImage]));
		w7.Resize = false;
		this.hpaned3.Add (this.vpaned2);
		global::Gtk.Paned.PanedChild w8 = ((global::Gtk.Paned.PanedChild)(this.hpaned3 [this.vpaned2]));
		w8.Resize = false;
		this.vpaned1.Add (this.hpaned3);
		this.hpaned1.Add (this.vpaned1);
		this.hbox2.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hpaned1]));
		w11.Position = 1;
		this.hbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox2]));
		w12.Position = 1;
		this.vbox2.Add (this.hbox1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
		w13.Position = 1;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1072;
		this.DefaultHeight = 551;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.quitAction1.Activated += new global::System.EventHandler (this.act);
		this.ColWiseAction.Toggled += new global::System.EventHandler (this.OnColWise);
		this.RowwiseAction.Toggled += new global::System.EventHandler (this.OnRowWise);
		this.RowwiseSelector.Toggled += new global::System.EventHandler (this.RowwiseChanged);
		this.RowwiseAction1.Toggled += new global::System.EventHandler (this.t);
		this.RowwiseAction1.Activated += new global::System.EventHandler (this.a);
		this.RowwiseAction1.Changed += new global::Gtk.ChangedHandler (this.c);
		this.ColumnWiseAction.Toggled += new global::System.EventHandler (this.ModeToggled);
		this.spinbutton.Changed += new global::System.EventHandler (this.SpinChanged);
		this.filechooserwidget.FileActivated += new global::System.EventHandler (this.fileSelected);
	}
}
